### PCA and PLS

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
# import dataset
myDF = pd.read_excel("/Users/rauns/Downloads/lowarp.xlsx") # input your own dataset here, could be csv or excel

In [3]:
myDF

Primary ID  Obs. Sec. ID:1  glas  crtp  mica  amtp  wrp1  wrp2  wrp3  \
0            1               1    40    10    10    40   0.9   5.0   0.2   
1            2               2    20    20     0    60   3.7   7.3   0.7   
2            3               3    40    20     0    40   3.6   6.9   0.9   
3            4               4    20    20    20    40   0.6   3.1   0.3   
4            5               5    20    10    20    50   0.3   2.1   0.3   
5            6               6    40     0    20    40   1.2   5.0   NaN   
6            7               7    20     0    20    60   2.3   3.9   0.3   
7            8               8    40     0    10    50   2.6   5.9   0.4   
8            9               9    30    20    10    40   2.2   5.3   0.2   
9           10              10    40     0     0    60   5.8   7.0   0.9   
10          11              11    30     0    20    50   0.8   2.9   0.5   
11          12              12    30    10     0    60   2.8   5.1   1.0   
12          13              13    30    10    10    50   1.1   4.7   0.6   
13          14              14    30    10    10    50   1.9   4.7   1.0   
14          15              15    30    10    10    50   2.9   5.9   0.5   
15          16              16    40    10     0    50   5.5   7.9   0.8   
16          17              17    30     0    10    60   3.2   6.0   0.3   

    wrp4  wrp5  wrp6  st1    st2  wrp7   st3    st4  wrp8   st5  st6  
0    1.0   0.3   4.2  232  15120   1.2  2190  26390   1.3  2400  0.7  
1    1.8   2.5   5.4  150  12230   1.8   905  20270   2.1  1020  0.6  
2    2.1   4.8   9.4  243  15550   1.2  1740  21180   1.4  1640  NaN  
3    0.4   0.4   1.1  188  11080   1.0  1700  17630   1.0  1860  0.5  
4    0.3   0.8   1.1  172  11960   1.2  1810  21070   1.3  1970  0.5  
5    NaN   NaN   NaN  245  15600   1.1  2590  25310   1.3  2490  0.6  
6    0.4   0.7   1.4  242  13900   1.5  1890  21370   1.6  1780  NaN  
7    0.2   0.7   1.2  243  17290   1.6  2130  30530   1.6  2320  0.7  
8    0.7   0.6   2.0  204  11170   1.0  1670  19070   1.1  1890  0.6  
9    1.0   5.6  11.8  262  20160   1.6  1930  29830   1.8  1890  NaN  
10   0.6   1.1   2.0  225  14140   1.3  2140  22850   1.3  2110  0.7  
11   1.2   2.7   6.1  184  15170   1.9  1230  23400   2.1  1250  0.6  
12   0.9   1.3   3.5  198  13420   1.4  1750  23790   1.4  1930  0.7  
13   1.0   2.8   5.4  234  16970   1.5  1920  25010   1.6  1790  0.7  
14   0.6   1.0   6.6  239  15480   1.5  1800  23140   1.6  1730  NaN  
15   2.4   5.5   9.3  256  18870   1.5  1880  28440   1.8  1790  NaN  
16   0.5   1.5   5.2  249  16310   1.5  1860  24710   1.7  1780  NaN

In [4]:
myDF.shape

(17, 20)

In [5]:
myDF.isnull().sum()

Primary ID        0
Obs. Sec. ID:1    0
glas              0
crtp              0
mica              0
amtp              0
wrp1              0
wrp2              0
wrp3              1
wrp4              1
wrp5              1
wrp6              1
st1               0
st2               0
wrp7              0
st3               0
st4               0
wrp8              0
st5               0
st6               6
dtype: int64

In [6]:
myDF = myDF.fillna(myDF.mean())
myDF

Primary ID  Obs. Sec. ID:1  glas  crtp  mica  amtp  wrp1  wrp2     wrp3  \
0            1               1    40    10    10    40   0.9   5.0  0.20000   
1            2               2    20    20     0    60   3.7   7.3  0.70000   
2            3               3    40    20     0    40   3.6   6.9  0.90000   
3            4               4    20    20    20    40   0.6   3.1  0.30000   
4            5               5    20    10    20    50   0.3   2.1  0.30000   
5            6               6    40     0    20    40   1.2   5.0  0.55625   
6            7               7    20     0    20    60   2.3   3.9  0.30000   
7            8               8    40     0    10    50   2.6   5.9  0.40000   
8            9               9    30    20    10    40   2.2   5.3  0.20000   
9           10              10    40     0     0    60   5.8   7.0  0.90000   
10          11              11    30     0    20    50   0.8   2.9  0.50000   
11          12              12    30    10     0    60   2.8   5.1  1.00000   
12          13              13    30    10    10    50   1.1   4.7  0.60000   
13          14              14    30    10    10    50   1.9   4.7  1.00000   
14          15              15    30    10    10    50   2.9   5.9  0.50000   
15          16              16    40    10     0    50   5.5   7.9  0.80000   
16          17              17    30     0    10    60   3.2   6.0  0.30000   

       wrp4     wrp5      wrp6  st1    st2  wrp7   st3    st4  wrp8   st5  \
0   1.00000  0.30000   4.20000  232  15120   1.2  2190  26390   1.3  2400   
1   1.80000  2.50000   5.40000  150  12230   1.8   905  20270   2.1  1020   
2   2.10000  4.80000   9.40000  243  15550   1.2  1740  21180   1.4  1640   
3   0.40000  0.40000   1.10000  188  11080   1.0  1700  17630   1.0  1860   
4   0.30000  0.80000   1.10000  172  11960   1.2  1810  21070   1.3  1970   
5   0.94375  2.01875   4.73125  245  15600   1.1  2590  25310   1.3  2490   
6   0.40000  0.70000   1.40000  242  13900   1.5  1890  21370   1.6  1780   
7   0.20000  0.70000   1.20000  243  17290   1.6  2130  30530   1.6  2320   
8   0.70000  0.60000   2.00000  204  11170   1.0  1670  19070   1.1  1890   
9   1.00000  5.60000  11.80000  262  20160   1.6  1930  29830   1.8  1890   
10  0.60000  1.10000   2.00000  225  14140   1.3  2140  22850   1.3  2110   
11  1.20000  2.70000   6.10000  184  15170   1.9  1230  23400   2.1  1250   
12  0.90000  1.30000   3.50000  198  13420   1.4  1750  23790   1.4  1930   
13  1.00000  2.80000   5.40000  234  16970   1.5  1920  25010   1.6  1790   
14  0.60000  1.00000   6.60000  239  15480   1.5  1800  23140   1.6  1730   
15  2.40000  5.50000   9.30000  256  18870   1.5  1880  28440   1.8  1790   
16  0.50000  1.50000   5.20000  249  16310   1.5  1860  24710   1.7  1780   

         st6  
0   0.700000  
1   0.600000  
2   0.627273  
3   0.500000  
4   0.500000  
5   0.600000  
6   0.627273  
7   0.700000  
8   0.600000  
9   0.627273  
10  0.700000  
11  0.600000  
12  0.700000  
13  0.700000  
14  0.627273  
15  0.627273  
16  0.627273

In [7]:
pca_df = myDF
pca_df.drop(["Primary ID", "Obs. Sec. ID:1"], axis=1, inplace=True)
pca_df

glas  crtp  mica  amtp  wrp1  wrp2     wrp3     wrp4     wrp5      wrp6  \
0     40    10    10    40   0.9   5.0  0.20000  1.00000  0.30000   4.20000   
1     20    20     0    60   3.7   7.3  0.70000  1.80000  2.50000   5.40000   
2     40    20     0    40   3.6   6.9  0.90000  2.10000  4.80000   9.40000   
3     20    20    20    40   0.6   3.1  0.30000  0.40000  0.40000   1.10000   
4     20    10    20    50   0.3   2.1  0.30000  0.30000  0.80000   1.10000   
5     40     0    20    40   1.2   5.0  0.55625  0.94375  2.01875   4.73125   
6     20     0    20    60   2.3   3.9  0.30000  0.40000  0.70000   1.40000   
7     40     0    10    50   2.6   5.9  0.40000  0.20000  0.70000   1.20000   
8     30    20    10    40   2.2   5.3  0.20000  0.70000  0.60000   2.00000   
9     40     0     0    60   5.8   7.0  0.90000  1.00000  5.60000  11.80000   
10    30     0    20    50   0.8   2.9  0.50000  0.60000  1.10000   2.00000   
11    30    10     0    60   2.8   5.1  1.00000  1.20000  2.70000   6.10000   
12    30    10    10    50   1.1   4.7  0.60000  0.90000  1.30000   3.50000   
13    30    10    10    50   1.9   4.7  1.00000  1.00000  2.80000   5.40000   
14    30    10    10    50   2.9   5.9  0.50000  0.60000  1.00000   6.60000   
15    40    10     0    50   5.5   7.9  0.80000  2.40000  5.50000   9.30000   
16    30     0    10    60   3.2   6.0  0.30000  0.50000  1.50000   5.20000   

    st1    st2  wrp7   st3    st4  wrp8   st5       st6  
0   232  15120   1.2  2190  26390   1.3  2400  0.700000  
1   150  12230   1.8   905  20270   2.1  1020  0.600000  
2   243  15550   1.2  1740  21180   1.4  1640  0.627273  
3   188  11080   1.0  1700  17630   1.0  1860  0.500000  
4   172  11960   1.2  1810  21070   1.3  1970  0.500000  
5   245  15600   1.1  2590  25310   1.3  2490  0.600000  
6   242  13900   1.5  1890  21370   1.6  1780  0.627273  
7   243  17290   1.6  2130  30530   1.6  2320  0.700000  
8   204  11170   1.0  1670  19070   1.1  1890  0.600000  
9   262  20160   1.6  1930  29830   1.8  1890  0.627273  
10  225  14140   1.3  2140  22850   1.3  2110  0.700000  
11  184  15170   1.9  1230  23400   2.1  1250  0.600000  
12  198  13420   1.4  1750  23790   1.4  1930  0.700000  
13  234  16970   1.5  1920  25010   1.6  1790  0.700000  
14  239  15480   1.5  1800  23140   1.6  1730  0.627273  
15  256  18870   1.5  1880  28440   1.8  1790  0.627273  
16  249  16310   1.5  1860  24710   1.7  1780  0.627273

In [8]:
scaler = StandardScaler()
scaler.fit(pca_df)

StandardScaler()

In [9]:
scaled_data = scaler.transform(pca_df)
scaled_data

array([[ 1.16422579e+00,  1.55230105e-01,  0.00000000e+00,
        -1.30384048e+00, -9.85502265e-01, -1.40071148e-01,
        -1.30888593e+00,  9.22592508e-02, -1.01026501e+00,
        -1.70123655e-01,  3.30931631e-01,  6.20851547e-02,
        -7.93492048e-01,  9.98390460e-01,  7.48788294e-01,
        -7.58462096e-01,  1.51620307e+00,  1.20604538e+00],
       [-1.47468600e+00,  1.47468600e+00, -1.30384048e+00,
         1.30384048e+00,  8.11812210e-01,  1.34014018e+00,
         5.28146955e-01,  1.40439082e+00,  2.82874203e-01,
         2.14155660e-01, -2.26074642e+00, -1.10212998e+00,
         1.58698410e+00, -2.57992613e+00, -9.96371521e-01,
         1.88643137e+00, -2.36699824e+00, -4.52267017e-01],
       [ 1.16422579e+00,  1.47468600e+00, -1.30384048e+00,
        -1.30384048e+00,  7.47622408e-01,  1.08271212e+00,
         1.26296011e+00,  1.89644016e+00,  1.63479247e+00,
         1.49508671e+00,  6.78595760e-01,  2.35307475e-01,
        -7.93492048e-01, -2.54716516e-01, -7.36878803e

In [10]:
pca = PCA(n_components = 4) # n components is the number of components you want to reduce the dimensions to 

In [11]:
pca.fit(scaled_data)

PCA(n_components=4)

In [12]:
components = pca.transform(scaled_data)

In [13]:
scaled_data.shape

(17, 18)

In [14]:
components.shape

(17, 4)

In [15]:
pca_values_df = pd.DataFrame(data = components, columns = ['Principal Component 1', 'Principal Component 2', 
                                                           'Principal Component 3', 'Principal Component 4'])
pca_values_df

Principal Component 1  Principal Component 2  Principal Component 3  \
0               -1.420884              -2.548788               1.006698   
1                2.211661               5.611065              -0.449455   
2                2.503607               0.426262               3.706768   
3               -4.898244               1.895117               1.570977   
4               -4.223683               1.456388              -0.518975   
5               -1.384516              -3.394026               1.021557   
6               -1.746095               0.202160              -2.549655   
7                0.264525              -2.974759              -1.802686   
8               -2.906411               1.029111               2.120113   
9                5.168083              -1.725479              -0.531459   
10              -2.295390              -1.532479              -1.071718   
11               2.640922               3.154262              -1.470894   
12              -0.903140               0.201463              -0.204244   
13               1.089137              -0.461229              -0.266695   
14               0.321137               0.093268              -0.328525   
15               4.916968              -0.836727               1.594624   
16               0.662323              -0.595610              -1.826432   

    Principal Component 4  
0                1.660019  
1                0.887436  
2               -0.028282  
3               -1.102223  
4               -1.403030  
5               -0.848427  
6               -0.825105  
7                1.280812  
8                0.508852  
9               -1.607281  
10               0.426253  
11               0.310129  
12               1.449991  
13               0.585318  
14              -0.081379  
15              -0.556045  
16              -0.657039

### Algorithm #2: Partial Least Squares (PLS)

In [16]:
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_predict

In [17]:
# The goal is to predict y from x
X = np.array([pca_df['glas'], pca_df['crtp'], pca_df['mica'], pca_df['amtp']]) # x matrix, predictors var
Y = np.array([pca_df['wrp1'], pca_df['wrp2'], pca_df['wrp3'], pca_df['wrp4'], pca_df['wrp5'], pca_df['wrp6'], 
     pca_df['wrp7'], pca_df['wrp8'], 
     pca_df['st1'], pca_df['st2'], pca_df['st3'], pca_df['st4'], pca_df['st5'], pca_df['st6']]) # y matrix, reponse var 

In [18]:
# Define PLS object and choose number of components
pls = PLSRegression(n_components=4)

In [19]:
X.transpose().shape

(17, 4)

In [20]:
X.transpose()

array([[40, 10, 10, 40],
       [20, 20,  0, 60],
       [40, 20,  0, 40],
       [20, 20, 20, 40],
       [20, 10, 20, 50],
       [40,  0, 20, 40],
       [20,  0, 20, 60],
       [40,  0, 10, 50],
       [30, 20, 10, 40],
       [40,  0,  0, 60],
       [30,  0, 20, 50],
       [30, 10,  0, 60],
       [30, 10, 10, 50],
       [30, 10, 10, 50],
       [30, 10, 10, 50],
       [40, 10,  0, 50],
       [30,  0, 10, 60]], dtype=int64)

In [21]:
Y.transpose().shape

(17, 14)

In [22]:
Y.transpose()

array([[9.00000000e-01, 5.00000000e+00, 2.00000000e-01, 1.00000000e+00,
        3.00000000e-01, 4.20000000e+00, 1.20000000e+00, 1.30000000e+00,
        2.32000000e+02, 1.51200000e+04, 2.19000000e+03, 2.63900000e+04,
        2.40000000e+03, 7.00000000e-01],
       [3.70000000e+00, 7.30000000e+00, 7.00000000e-01, 1.80000000e+00,
        2.50000000e+00, 5.40000000e+00, 1.80000000e+00, 2.10000000e+00,
        1.50000000e+02, 1.22300000e+04, 9.05000000e+02, 2.02700000e+04,
        1.02000000e+03, 6.00000000e-01],
       [3.60000000e+00, 6.90000000e+00, 9.00000000e-01, 2.10000000e+00,
        4.80000000e+00, 9.40000000e+00, 1.20000000e+00, 1.40000000e+00,
        2.43000000e+02, 1.55500000e+04, 1.74000000e+03, 2.11800000e+04,
        1.64000000e+03, 6.27272727e-01],
       [6.00000000e-01, 3.10000000e+00, 3.00000000e-01, 4.00000000e-01,
        4.00000000e-01, 1.10000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.88000000e+02, 1.10800000e+04, 1.70000000e+03, 1.76300000e+04,
        1.860

In [23]:
# Fit
pls.fit(X.transpose(), Y.transpose())

C:\Users\rauns\Anaconda3\lib\site-packages\sklearn\cross_decomposition\_pls.py:353: UserWarning: X scores are null at iteration 3
  warnings.warn('X scores are null at iteration %s' % k)


PLSRegression(n_components=4)

In [24]:
# Cross-validation
y_cv = cross_val_predict(pls, X.transpose(), Y.transpose(), cv=10)
y_cv

C:\Users\rauns\Anaconda3\lib\site-packages\sklearn\cross_decomposition\_pls.py:353: UserWarning: X scores are null at iteration 3
  warnings.warn('X scores are null at iteration %s' % k)
C:\Users\rauns\Anaconda3\lib\site-packages\sklearn\cross_decomposition\_pls.py:353: UserWarning: X scores are null at iteration 3
  warnings.warn('X scores are null at iteration %s' % k)
C:\Users\rauns\Anaconda3\lib\site-packages\sklearn\cross_decomposition\_pls.py:353: UserWarning: X scores are null at iteration 3
  warnings.warn('X scores are null at iteration %s' % k)
C:\Users\rauns\Anaconda3\lib\site-packages\sklearn\cross_decomposition\_pls.py:353: UserWarning: X scores are null at iteration 3
  warnings.warn('X scores are null at iteration %s' % k)
C:\Users\rauns\Anaconda3\lib\site-packages\sklearn\cross_decomposition\_pls.py:353: UserWarning: X scores are null at iteration 3
  warnings.warn('X scores are null at iteration %s' % k)
C:\Users\rauns\Anaconda3\lib\site-packages\sklearn\cross_decompos

array([[ 2.51605874e+00,  5.98735197e+00,  6.13690194e-01,
         1.25106585e+00,  2.75248697e+00,  5.64258645e+00,
         1.17318806e+00,  1.30525817e+00,  2.40921838e+02,
         1.57532260e+04,  2.15936523e+03,  2.49852108e+04,
         2.17356703e+03,  6.40695922e-01],
       [ 3.49403126e+00,  5.13036476e+00,  7.45492361e-01,
         1.13574876e+00,  2.69174710e+00,  6.37579198e+00,
         1.67766461e+00,  1.83344387e+00,  1.86232591e+02,
         1.36934912e+04,  9.67404074e+02,  1.97561606e+04,
         1.02593084e+03,  5.70634340e-01],
       [ 3.08373684e+00,  7.09700000e+00,  6.36934211e-01,
         1.70511842e+00,  2.70948684e+00,  6.83709211e+00,
         1.30810526e+00,  1.49489474e+00,  2.10570526e+02,
         1.51604632e+04,  1.71680526e+03,  2.52185842e+04,
         1.89930526e+03,  6.50186603e-01],
       [-5.98052632e-01,  2.97900000e+00,  1.87486842e-01,
         6.43723684e-01, -9.67802632e-01, -8.00881579e-01,
         1.03042105e+00,  1.09057895e+00,  1.

In [25]:
# Calculate r^2 score, goodness of fit
score = r2_score(Y.transpose(), y_cv)
score

0.5094414435151496

In [26]:
# mean squares error, average squared difference between the estimated values and the actual value
mse = mean_squared_error(Y.transpose(), y_cv)
mse

364344.985189675

References:
    - https://nirpyresearch.com/partial-least-squares-regression-python/
    - https://scikit-learn.org/stable/modules/generated/sklearn.cross_decomposition.PLSRegression.html
    - https://www.casact.org/pubs/dpp/dpp08/08dpp76.pdf
    - https://ogrisel.github.io/scikit-learn.org/sklearn-tutorial/auto_examples/plot_pls.html